stages:
  data_ingestion:
    cmd: python src/fnd/component/s1_data_ingestion.py
    deps:
      - src/fnd/component/s1_data_ingestion.py
    outs:
      - artifacts/data_ingestion

  data_validation:
    cmd: python src/fnd/component/s2_data_validation.py
    deps:
      - src/fnd/component/s2_data_validation.py
      - artifacts/data_ingestion

  data_preprocessing:
    cmd: python src/fnd/component/s3_data_preprocessing.py
    deps:
      - src/fnd/component/s3_data_preprocessing.py
      - artifacts/data_ingestion
    outs:
      - artifacts/data_preprocessing

  data_transformation:
    cmd: python src/fnd/component/s4_data_transformation.py
    deps:
      - src/fnd/component/s4_data_transformation.py
      - artifacts/data_preprocessing
    outs:
      - artifacts/data_transformation

  model_training:
    cmd: python src/fnd/component/s5_model_training.py
    deps:
      - src/fnd/component/s5_model_training.py
      - src/fnd/component/model.py
      - artifacts/data_transformation
    outs:
      - artifacts/model

  model_evaluation:
    cmd: python src/fnd/component/s6_model_evaluation.py
    deps:
      - src/fnd/component/s6_model_evaluation.py
      - artifacts/model
    outs:
      - artifacts/evaluation
