artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  download_path: artifacts/data_ingestion/LIAR_Dataset

data_validation:
  train_data_path: artifacts/data_ingestion/LIAR_Dataset/train.csv
  test_data_path: artifacts/data_ingestion/LIAR_Dataset/test.csv
  valid_data_path: artifacts/data_ingestion/LIAR_Dataset/valid.csv

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  train_data_path: artifacts/data_ingestion/LIAR_Dataset/train.csv
  test_data_path: artifacts/data_ingestion/LIAR_Dataset/test.csv
  vectorizer_path: artifacts/data_preprocessing

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_preprocessing/train_preprocessed.csv
  test_data_path: artifacts/data_preprocessing/test_preprocessed.csv

model_training:
  root_dir: artifacts/model
  train_X_path: artifacts/data_transformation/train/X.npy
  train_y_path: artifacts/data_transformation/train/y.npy

model_evaluation:
  root_dir: artifacts/evaluation
  test_X_path: artifacts/data_transformation/test/X.npy
  test_y_path: artifacts/data_transformation/test/y.npy
  model_path: artifacts/model/model.pkl
  metrics_path: artifacts/evaluation

experiment_tracking:
  repo_name: Test_FakeNewsDetection
  repo_owner: aakash-dec7
  mlflow:
    uri: https://dagshub.com/aakash-dec7/Test_FakeNewsDetection.mlflow

prediction:
  model_path: artifacts/model/model.pkl
  vectorizer_path: artifacts/data_preprocessing/vectorizer.bin
